### ISSUE TITLE
Does the library supports signing multiple hashes in a single APi call?

### ISSUE THREAD

**Issue by OlexandrPopov** [Setasign/SetaPDF-Signer-Addon-CSC#8]
According to the CSC API specifications ([v1](https://cloudsignatureconsortium.org/wp-content/uploads/2020/01/CSC_API_V1_1.0.4.0.pdf) and [v2](https://cloudsignatureconsortium.org/wp-content/uploads/2023/04/csc-api-v2.0.0.2.pdf)) it should be possible to sign one or more hash values. 

If signing multiple hashes is supported could you post a usage example?

**Comment by JanSlabon** [comment]
The `$hash` parameter of the client class is an array, which accepts multiple hashes.
Anyhow there's no demonstration for this atm nor you can use the `Module` class directly because such workflow is simliar to an asynchronous signature and the signature values need be be created outside of the module. We demoed this for a single signature [here](https://github.com/Setasign/SetaPDF-Signer-Addon-CSC/blob/main/examples/async-demo.php).

**Comment by OlexandrPopov** [comment]
I'll scrutinize the linked sample later, but at first glance that should work. I'm closing this ticket.
Thank you very much!

**Comment by OlexandrPopov** [comment]
The sample linked above seems to be working with a single signature, though in the case when there is at least two signatures it fails with this error:

```
 SetaPDF_Signer_ValidationRelatedInfo_Exception  : Signature integrity is invalid (Status: -3).

  at /var/www/html/vendor/setasign/setapdf-signer/library/SetaPDF/Signer/ValidationRelatedInfo/Collector.php:1198
    1194|     )
    1195|     {
    1196|         $integrityResult = IntegrityResult::create($document, $fieldName);
    1197|         if (!$integrityResult->isValid()) {
  > 1198|             throw new SetaPDF_Signer_ValidationRelatedInfo_Exception(
    1199|                 sprintf('Signature integrity is invalid (Status: %d).', $integrityResult->getStatus())
    1200|             );
    1201|         }
```
Do you have any ideas about what might be the cause of the problem?

**Comment by OlexandrPopov** [comment]
I think I solved it. It looks like a new instance of `SetaPDF_Signer_Signature_Module_Pades` should be created for each of file that needs to be signed.

**Comment by JanSlabon** [comment]
> I'm curious if it's possible to recreate the module completely on the "preSign" and "sign" actions instead of storing it in the session.

This should be possible.
